package enums

enum class OperationType {
    PURCHASE, REFUND,REVERSAL,AUTO_REVERSAL,AUTHORISATION,AUTHORISATION_CONFIRMATION,RECONCILIATION,
    KEY_ACCEPT,CHECK_CONNECT, BALANCE_INQUIRY, PURCHASE_WITH_CASH_BACK, EMV_FINAL_ADVICE, GET_AUTH_KEYS, REPEAT, PURCHASE_RETURN
}